[tool.poetry]
name = "ml-mlflow"
version = "2.13.0-1"
description = "Container setup for mlflow for ml experiment tracking"
authors = ["Clemens Kriechbaumer <clemens.kriechbaumer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mlflow = "^2.13.0"
psycopg2-binary = "^2.9.9"
boto3 = "^1.34.109"
prometheus-flask-exporter = "^0.23.0"
azure-storage-blob = "^12.20.0"
azure-identity = "^1.16.0"
gevent = "^24.2.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.4"
black = "^24.3.0"

[tool.poetry.group.genai.dependencies]
mlflow = {extras = ["genai"], version = "^2.13.0"}

[tool.poetry.group.samples.dependencies]
langchain = "^0.1.20"

