[tool.poetry]
name = "ml-mlflow"
version = "2.10.0-1"
description = "Container setup for mlflow for ml experiment tracking"
authors = ["Clemens Kriechbaumer <clemens.kriechbaumer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
mlflow = "^2.10.2"
psycopg2-binary = "^2.9.9"
boto3 = "^1.34.46"
prometheus-flask-exporter = "^0.23.0"
azure-storage-blob = "^12.19.0"
azure-identity = "^1.15.0"
gevent = "^24.2.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.2.2"
black = "^24.2.0"

