[tool.poetry]
name = "ml-mlflow"
version = "2.7.1-1"
description = "Container setup for mlflow for ml experiment tracking"
authors = ["Clemens Kriechbaumer <clemens.kriechbaumer@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mlflow = "^2.7.1"
psycopg2-binary = "^2.9.9"
boto3 = "^1.28.63"
prometheus-flask-exporter = "^0.22.4"
