version: '3'

networks:
  mlflow-network:

services:
  mlflow-db:
    container_name: mlflow-db
    image: postgres
    restart: always
    networks:
      - mlflow-network
    expose:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=mlflow
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data      
    
  mlflow:
    container_name: mlflow
    image: localhost/mlflow:latest
    restart: always
    depends_on:
      - mlflow-db
    ports:
      - "${MLFLOW_PORT}:5000"
    networks:
      - mlflow-network
    environment:
      # azure
      # - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      #- AZURE_STORAGE_ACCESS_KEY=${AZURE_STORAGE_ACCESS_KEY}
      # s3      
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
      - MLFLOW_S3_IGNORE_TLS=${MLFLOW_S3_IGNORE_TLS}      
      # backend
      - MLFLOW_BACKEND_STORE_URI=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@mlflow-db:5432/mlflow
      # storage
      - MLFLOW_ARTIFACTS_DESTINATION=${MLFLOW_ARTIFACTS_DESTINATION}
    command: "server"