endpoints:
  - name: internal-completions-openai-gpt-3.5-turbo
    endpoint_type: llm/v1/completions
    model:
      provider: openai
      name: gpt-3.5-turbo
      config:
        openai_api_key: $OPENAI_API_KEY
    limit:
      renewal_period: minute
      calls: 10

  - name: internal-completions-openai-gpt-4-turbo
    endpoint_type: llm/v1/completions
    model:
      provider: openai
      name: gpt-4-turbo-2024-04-09
      config:
        openai_api_key: $OPENAI_API_KEY
    limit:
      renewal_period: minute
      calls: 10

  - name: internal-chat-openai-gpt-3.5-turbo
    endpoint_type: llm/v1/chat
    model:
      provider: openai
      name: gpt-3.5-turbo
      config:
        openai_api_key: $OPENAI_API_KEY

  - name: internal-chat-openai-gpt-4-turbo
    endpoint_type: llm/v1/chat
    model:
      provider: openai
      name: gpt-4-turbo-2024-04-09
      config:
        openai_api_key: $OPENAI_API_KEY

  - name: internal-embeddings-openai-text-embedding-3-large
    endpoint_type: llm/v1/embeddings
    model:
      provider: openai
      name: text-embedding-3-large
      config:
        openai_api_key: $OPENAI_API_KEY2

  # anthropic embeddings not yet supported
  # - name: internal-embeddings-anthropic-voyage-large-2
  #   endpoint_type: llm/v1/embeddings
  #   model:
  #     provider: anthropic
  #     name: voyage-large-2
  #     config:
  #       anthropic_api_key: $ANTHROPIC_API_KEY

  - name: internal-chat-anthropic-claude-3-opus-20240229
    endpoint_type: llm/v1/chat
    model:
      provider: anthropic
      name: claude-3-opus-20240229
      config:
        anthropic_api_key: $ANTHROPIC_API_KEY
